#!/usr/bin/env python3
"""Generate and (optionally) apply the BigQuery remote functions for the FPE demo.

One Cloud Run service backs every function; the function's user_defined_context
carries the mode, and max_batching_rows is baked into the function name so a
sweep can switch batch size purely in SQL, with no redeploy.

    python fpe/scripts/generate_remote_functions.py            # write SQL only
    python fpe/scripts/generate_remote_functions.py --apply    # write + execute

Naming: fpe_<mode>_b<batch>  e.g. fpe_decrypt_b1000, fpe_noop_b10000
plus unsuffixed fpe_encrypt / fpe_decrypt at the default batch size for demo use.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from config._loader import load, require  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

from calibration import CONTAINER  # noqa: E402
from workloads import WORKLOADS  # noqa: E402

#: Batch sizes for the main performance sweep.
BATCH_SIZES = [100, 500, 1000, 2500, 5000, 10000, 25000, 50000]

#: `rounds` values for the container calibration probe. Spans two orders of
#: magnitude so the fit is not anchored on one point, and starts low because
#: the interesting end of the study — a native-code PEP at single-digit µs/row —
#: lives there. Small batch: these requests should be short, not saturating.
CALIBRATION_ROUNDS = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
CALIBRATION_BATCH = 2500

#: Oversized batches used only to probe BigQuery's documented ceilings:
#:   HTTP response size (Cloud Run / gen2) = 15 MB
#: At ~14 B/row for an SSN reply these are all still safe; the point is to find
#: where BigQuery *actually* stops honouring max_batching_rows, which the docs
#: describe only as "a cap", never as a promise.
LIMIT_BATCH_SIZES = [100000, 250000, 500000, 1000000]

#: mode -> (extra user_defined_context, batch sizes to generate)
MODES: dict[str, tuple[dict, list[int]]] = {
    "fpe_encrypt": ({}, BATCH_SIZES + LIMIT_BATCH_SIZES),
    "fpe_decrypt": ({}, BATCH_SIZES + LIMIT_BATCH_SIZES),
    "hmac": ({}, BATCH_SIZES),
    "noop": ({}, BATCH_SIZES + LIMIT_BATCH_SIZES),
    "cpu": ({"rounds": "100"}, BATCH_SIZES),
    "io": ({"sleep_ms": "50"}, BATCH_SIZES),
    # 1000 chars/row: 15 MB response ceiling is crossed somewhere around
    # 15k rows, so these bracket it deliberately.
    "bloat": ({"width": "1000"}, [1000, 5000, 10000, 15000, 20000, 50000]),
    # Always-fail and half-fail variants for the retry-behaviour probe.
    "error": ({"fail_pct": "100", "fail_code": "503"}, [1000]),
}

#: Extra one-off functions that don't fit the mode x batch grid.
EXTRA: list[tuple[str, dict, int]] = [
    # 50% failure rate: shows BigQuery retrying and eventually succeeding.
    ("error_half_b1000", {"mode": "error", "fail_pct": "50", "fail_code": "503"}, 1000),
    # Non-retryable status: BigQuery should fail the query immediately.
    ("error_400_b1000", {"mode": "error", "fail_pct": "100", "fail_code": "400"}, 1000),
    # Default batching: BigQuery chooses. Its choice is itself a finding.
    ("fpe_decrypt_auto", {"mode": "fpe_decrypt"}, None),
] + [
    # Response-size ceiling probe. BigQuery caps a request near 11,905 rows
    # regardless of max_batching_rows, so the only way to cross the 15 MB
    # response limit is to widen each reply rather than add rows.
    (f"bloat_w{w}", {"mode": "bloat", "width": str(w)}, 50000)
    for w in (1000, 1200, 1500, 2000, 3000)
]

DEFAULT_BATCH = 1000

HEADER = """\
-- Generated by fpe/scripts/generate_remote_functions.py -- DO NOT EDIT BY HAND.
--
-- One Cloud Run service ({service}) backs all of these. The function's
-- user_defined_context selects the mode; max_batching_rows is fixed per
-- function so the perf sweep can change batch size without redeploying.
--
-- Project:    {project}
-- Dataset:    {dataset}
-- Connection: {connection}
-- Endpoint:   {endpoint}
"""

TEMPLATE = """
CREATE OR REPLACE FUNCTION `{project}.{dataset}`.{name}(val STRING, data_element STRING)
RETURNS STRING
REMOTE WITH CONNECTION `{connection}`
OPTIONS (
  endpoint = '{endpoint}',
  user_defined_context = [{context}]{batch_opt}
);
"""


def _context(mode: str, extra: dict) -> str:
    pairs = [("mode", mode)] + sorted(extra.items())
    return ", ".join(f"('{k}', '{v}')" for k, v in pairs)


def _render(project, dataset, name, connection, endpoint, context, batch) -> str:
    # batch=None omits max_batching_rows entirely, letting BigQuery choose.
    batch_opt = f",\n  max_batching_rows = {batch}" if batch else ""
    return TEMPLATE.format(
        project=project, dataset=dataset, name=name, connection=connection,
        endpoint=endpoint, context=context, batch_opt=batch_opt,
    )


def build_sql(project: str, dataset: str, connection: str, endpoint: str) -> str:
    parts = [
        HEADER.format(
            project=project,
            dataset=dataset,
            connection=connection,
            endpoint=endpoint,
            service=endpoint.rsplit("/", 1)[-1],
        )
    ]

    parts.append("\n-- === Demo-facing functions (default batching) ===")
    for mode in ("fpe_encrypt", "fpe_decrypt"):
        parts.append(
            _render(project, dataset, mode, connection, endpoint,
                    _context(mode, MODES[mode][0]), DEFAULT_BATCH)
        )

    parts.append("\n-- === Sweep functions: <mode> x <max_batching_rows> ===")
    for mode, (extra, batches) in MODES.items():
        for batch in batches:
            parts.append(
                _render(project, dataset, f"{mode}_b{batch}", connection, endpoint,
                        _context(mode, extra), batch)
            )

    parts.append("\n-- === Limit / behaviour probes ===")
    for name, ctx, batch in EXTRA:
        mode = ctx.pop("mode")
        parts.append(
            _render(project, dataset, name, connection, endpoint,
                    _context(mode, ctx), batch)
        )

    parts.append(
        f"\n-- === Container CPU calibration (rounds -> µs/row) ===\n"
        f"-- Read by sweep.py --phase calibrate_cpu. Current container curve:\n"
        f"--   us_per_row = {CONTAINER.floor_us:.2f} "
        f"+ {CONTAINER.us_per_round:.4f} * rounds  ({CONTAINER.measured_on})"
    )
    for rounds in CALIBRATION_ROUNDS:
        parts.append(
            _render(project, dataset, f"cpu_r{rounds}_b{CALIBRATION_BATCH}",
                    connection, endpoint,
                    _context("cpu", {"rounds": str(rounds)}), CALIBRATION_BATCH)
        )

    parts.append(
        "\n-- === Scaling-study workload points (fpe/scripts/workloads.py) ===\n"
        "-- One function per point. The cost parameters are baked into the name,\n"
        "-- so re-calibrating the container curve renames the functions rather\n"
        "-- than silently changing what a stale name measures."
    )
    emitted = set(re.findall(r"\.(\w+)\(val STRING", "\n".join(parts)))
    for w in WORKLOADS.values():
        parts.append(
            f"-- {w.id}: {w.represents} "
            f"({w.cpu_us:g} µs CPU + {w.wait_ms} ms wait per row)"
        )
        if w.function in emitted:
            # W1/W4 reuse a mode x batch cell the grid above already defines;
            # re-emitting it would be a second CREATE OR REPLACE of the same body.
            parts.append(f"--   uses {w.function}, already defined above")
            continue
        emitted.add(w.function)
        parts.append(
            _render(project, dataset, w.function, connection, endpoint,
                    _context(w.mode, w.params), w.batch)
        )

    # Phase 3's batch-size sweep re-runs §7's batch question at a *cheap*
    # workload, where per-request overhead is a much larger share of the cost.
    cheap = WORKLOADS["W2"]
    parts.append(
        f"\n-- === Batch-size sweep at {cheap.id} "
        f"({cheap.cpu_us:g} µs/row) ===")
    for batch in BATCH_SIZES:
        if batch == cheap.batch:
            continue  # already emitted above
        parts.append(
            _render(project, dataset, f"{cheap.mode}{cheap.tag}_b{batch}",
                    connection, endpoint,
                    _context(cheap.mode, cheap.params), batch)
        )
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="execute the SQL via bq")
    ap.add_argument(
        "--out",
        default=str(REPO_ROOT / "fpe" / "sql" / "generated_remote_functions.sql"),
    )
    args = ap.parse_args()

    load()
    project = require("PROJECT_ID")
    dataset = require("FPE_DATASET")
    region = require("REGION")
    bq_location = require("BQ_LOCATION")
    connection = f"{project}.{bq_location.lower()}.{require('BQ_CONNECTION')}"

    endpoint = subprocess.run(
        [
            "gcloud", "run", "services", "describe", require("FPE_SERVICE"),
            f"--region={region}", f"--project={project}", "--format=value(status.url)",
        ],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    if not endpoint:
        print("ERROR: could not resolve the Cloud Run URL; deploy the service first.",
              file=sys.stderr)
        return 1

    sql = build_sql(project, dataset, connection, endpoint)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sql)
    n = sql.count("CREATE OR REPLACE FUNCTION")
    print(f"Wrote {n} function definitions to {out.relative_to(REPO_ROOT)}")

    if args.apply:
        print(f"Applying to {project}:{dataset} ...")
        # Pass the script on stdin: the SQL opens with a "--" comment, which bq
        # would otherwise parse as the start of a command-line flag.
        proc = subprocess.run(
            ["bq", f"--project_id={project}", "query", "--use_legacy_sql=false",
             "--nouse_cache", "--format=none"],
            input=sql, capture_output=True, text=True,
        )
        if proc.returncode != 0:
            print(proc.stdout + proc.stderr, file=sys.stderr)
            return proc.returncode
        print(f"Applied {n} functions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
