#!/usr/bin/env python3
"""Generate and (optionally) apply the BigQuery remote functions for the FPE demo.

One Cloud Run service backs every function; the function's user_defined_context
carries the mode, and max_batching_rows is baked into the function name so a
sweep can switch batch size purely in SQL, with no redeploy.

    python fpe/scripts/generate_remote_functions.py            # write SQL only
    python fpe/scripts/generate_remote_functions.py --apply    # write + execute

Naming: fpe_<mode>_b<batch>  e.g. fpe_decrypt_b1000, fpe_noop_b10000
plus unsuffixed fpe_encrypt / fpe_decrypt at the default batch size for demo use.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from config._loader import load, require  # noqa: E402

#: Batch sizes for the main performance sweep.
BATCH_SIZES = [100, 500, 1000, 2500, 5000, 10000, 25000, 50000]

#: Oversized batches used only to probe BigQuery's documented ceilings:
#:   HTTP response size (Cloud Run / gen2) = 15 MB
#: At ~14 B/row for an SSN reply these are all still safe; the point is to find
#: where BigQuery *actually* stops honouring max_batching_rows, which the docs
#: describe only as "a cap", never as a promise.
LIMIT_BATCH_SIZES = [100000, 250000, 500000, 1000000]

#: mode -> (extra user_defined_context, batch sizes to generate)
MODES: dict[str, tuple[dict, list[int]]] = {
    "fpe_encrypt": ({}, BATCH_SIZES + LIMIT_BATCH_SIZES),
    "fpe_decrypt": ({}, BATCH_SIZES + LIMIT_BATCH_SIZES),
    "hmac": ({}, BATCH_SIZES),
    "noop": ({}, BATCH_SIZES + LIMIT_BATCH_SIZES),
    "cpu": ({"rounds": "100"}, BATCH_SIZES),
    "io": ({"sleep_ms": "50"}, BATCH_SIZES),
    # 1000 chars/row: 15 MB response ceiling is crossed somewhere around
    # 15k rows, so these bracket it deliberately.
    "bloat": ({"width": "1000"}, [1000, 5000, 10000, 15000, 20000, 50000]),
    # Always-fail and half-fail variants for the retry-behaviour probe.
    "error": ({"fail_pct": "100", "fail_code": "503"}, [1000]),
}

#: Extra one-off functions that don't fit the mode x batch grid.
EXTRA: list[tuple[str, dict, int]] = [
    # 50% failure rate: shows BigQuery retrying and eventually succeeding.
    ("error_half_b1000", {"mode": "error", "fail_pct": "50", "fail_code": "503"}, 1000),
    # Non-retryable status: BigQuery should fail the query immediately.
    ("error_400_b1000", {"mode": "error", "fail_pct": "100", "fail_code": "400"}, 1000),
    # Default batching: BigQuery chooses. Its choice is itself a finding.
    ("fpe_decrypt_auto", {"mode": "fpe_decrypt"}, None),
] + [
    # Response-size ceiling probe. BigQuery caps a request near 11,905 rows
    # regardless of max_batching_rows, so the only way to cross the 15 MB
    # response limit is to widen each reply rather than add rows.
    (f"bloat_w{w}", {"mode": "bloat", "width": str(w)}, 50000)
    for w in (1000, 1200, 1500, 2000, 3000)
]

DEFAULT_BATCH = 1000

HEADER = """\
-- Generated by fpe/scripts/generate_remote_functions.py -- DO NOT EDIT BY HAND.
--
-- One Cloud Run service ({service}) backs all of these. The function's
-- user_defined_context selects the mode; max_batching_rows is fixed per
-- function so the perf sweep can change batch size without redeploying.
--
-- Project:    {project}
-- Dataset:    {dataset}
-- Connection: {connection}
-- Endpoint:   {endpoint}
"""

TEMPLATE = """
CREATE OR REPLACE FUNCTION `{project}.{dataset}`.{name}(val STRING, data_element STRING)
RETURNS STRING
REMOTE WITH CONNECTION `{connection}`
OPTIONS (
  endpoint = '{endpoint}',
  user_defined_context = [{context}]{batch_opt}
);
"""


def _context(mode: str, extra: dict) -> str:
    pairs = [("mode", mode)] + sorted(extra.items())
    return ", ".join(f"('{k}', '{v}')" for k, v in pairs)


def _render(project, dataset, name, connection, endpoint, context, batch) -> str:
    # batch=None omits max_batching_rows entirely, letting BigQuery choose.
    batch_opt = f",\n  max_batching_rows = {batch}" if batch else ""
    return TEMPLATE.format(
        project=project, dataset=dataset, name=name, connection=connection,
        endpoint=endpoint, context=context, batch_opt=batch_opt,
    )


def build_sql(project: str, dataset: str, connection: str, endpoint: str) -> str:
    parts = [
        HEADER.format(
            project=project,
            dataset=dataset,
            connection=connection,
            endpoint=endpoint,
            service=endpoint.rsplit("/", 1)[-1],
        )
    ]

    parts.append("\n-- === Demo-facing functions (default batching) ===")
    for mode in ("fpe_encrypt", "fpe_decrypt"):
        parts.append(
            _render(project, dataset, mode, connection, endpoint,
                    _context(mode, MODES[mode][0]), DEFAULT_BATCH)
        )

    parts.append("\n-- === Sweep functions: <mode> x <max_batching_rows> ===")
    for mode, (extra, batches) in MODES.items():
        for batch in batches:
            parts.append(
                _render(project, dataset, f"{mode}_b{batch}", connection, endpoint,
                        _context(mode, extra), batch)
            )

    parts.append("\n-- === Limit / behaviour probes ===")
    for name, ctx, batch in EXTRA:
        mode = ctx.pop("mode")
        parts.append(
            _render(project, dataset, name, connection, endpoint,
                    _context(mode, ctx), batch)
        )
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="execute the SQL via bq")
    ap.add_argument(
        "--out",
        default=str(REPO_ROOT / "fpe" / "sql" / "generated_remote_functions.sql"),
    )
    args = ap.parse_args()

    load()
    project = require("PROJECT_ID")
    dataset = require("FPE_DATASET")
    region = require("REGION")
    bq_location = require("BQ_LOCATION")
    connection = f"{project}.{bq_location.lower()}.{require('BQ_CONNECTION')}"

    endpoint = subprocess.run(
        [
            "gcloud", "run", "services", "describe", require("FPE_SERVICE"),
            f"--region={region}", f"--project={project}", "--format=value(status.url)",
        ],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    if not endpoint:
        print("ERROR: could not resolve the Cloud Run URL; deploy the service first.",
              file=sys.stderr)
        return 1

    sql = build_sql(project, dataset, connection, endpoint)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(sql)
    n = sql.count("CREATE OR REPLACE FUNCTION")
    print(f"Wrote {n} function definitions to {out.relative_to(REPO_ROOT)}")

    if args.apply:
        print(f"Applying to {project}:{dataset} ...")
        # Pass the script on stdin: the SQL opens with a "--" comment, which bq
        # would otherwise parse as the start of a command-line flag.
        proc = subprocess.run(
            ["bq", f"--project_id={project}", "query", "--use_legacy_sql=false",
             "--nouse_cache", "--format=none"],
            input=sql, capture_output=True, text=True,
        )
        if proc.returncode != 0:
            print(proc.stdout + proc.stderr, file=sys.stderr)
            return proc.returncode
        print(f"Applied {n} functions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
